# For production purposes
name: webcanape-bot

networks:
  proxy-manager:
    driver: bridge
    name: nginx-proxy-manager
    external: true

  database:
    driver: bridge
    name: database
    external: true

services:
  php:
    build: ./php
    volumes:
      - ../:/app
      - ../.runtime/cache/composer:/.composer/cache
    user: $USER_ID:$GROUP_ID
    working_dir: /app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - database
      - default

  cron:
    build:
      context: ./cron
      args:
        SCHEDULER_TOKEN: $SCHEDULER_TOKEN
    depends_on:
      - nginx
    volumes:
      - ../.runtime/logs/cron:/var/log/cron
    networks:
      - database
      - default
    command:
      - crond
      - "-f"
      - "-L"
      - "/dev/stdout"

  queue:
    build: ./queue
    volumes:
      - ../:/app
      - ../.runtime/cache/composer:/.composer/cache
      - ../.runtime/logs/php:/var/log/php
    user: $USER_ID:$GROUP_ID
    working_dir: /app
    depends_on:
      database:
        condition: service_healthy
    command:
      - php
      - artisan
      - queue:work
    networks:
      - database
      - default


  nginx:
    image: nginx:alpine
    volumes:
      - ../:/app:ro
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    working_dir: /app
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - proxy-manager
      - default
